#!/usr/bin/env bash
# =============================================================================
# Local Development Setup
# =============================================================================
# Generates RSA signing keys and a .env file for local Docker Compose testing.
# Run once before your first `docker compose up --build`.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KEYS_DIR="$PROJECT_ROOT/.keys"
ENV_FILE="$PROJECT_ROOT/.env"

# -- Colors (if terminal supports them) --------------------------------------
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  NC='\033[0m'
else
  GREEN='' YELLOW='' RED='' NC=''
fi

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# -- Prerequisites ------------------------------------------------------------
command -v docker  >/dev/null 2>&1 || error "docker is not installed"
command -v openssl >/dev/null 2>&1 || error "openssl is not installed"

# -- Generate RSA key pair ----------------------------------------------------
if [ -d "$KEYS_DIR" ] && [ -f "$KEYS_DIR/private.pem" ] && [ -f "$KEYS_DIR/public.pem" ]; then
  warn "Keys already exist in .keys/ — skipping generation"
else
  info "Generating RSA 2048-bit key pair in .keys/"
  mkdir -p "$KEYS_DIR"
  openssl genrsa -out "$KEYS_DIR/private.pem" 2048 2>/dev/null
  openssl rsa -in "$KEYS_DIR/private.pem" -pubout -out "$KEYS_DIR/public.pem" 2>/dev/null
  chmod 600 "$KEYS_DIR/private.pem"
  chmod 644 "$KEYS_DIR/public.pem"
  info "Keys generated successfully"
fi

# -- Base64-encode keys -------------------------------------------------------
if [[ "$(uname)" == "Darwin" ]]; then
  PRIVATE_KEY_B64=$(base64 -i "$KEYS_DIR/private.pem")
  PUBLIC_KEY_B64=$(base64 -i "$KEYS_DIR/public.pem")
else
  PRIVATE_KEY_B64=$(base64 -w0 "$KEYS_DIR/private.pem")
  PUBLIC_KEY_B64=$(base64 -w0 "$KEYS_DIR/public.pem")
fi

# -- Generate session secret --------------------------------------------------
SESSION_SECRET=$(openssl rand -base64 48)

# -- Create / update .env -----------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — updating signing keys and session secret only"

  # Helper: update or append a key=value pair
  update_env() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
      # Replace existing line (works on both macOS and Linux)
      if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
      else
        sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
      fi
    elif grep -q "^# *${key}=" "$ENV_FILE" 2>/dev/null; then
      # Uncomment and set
      if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "s|^# *${key}=.*|${key}=${value}|" "$ENV_FILE"
      else
        sed -i "s|^# *${key}=.*|${key}=${value}|" "$ENV_FILE"
      fi
    else
      echo "${key}=${value}" >> "$ENV_FILE"
    fi
  }

  update_env "OAUTH_SIGNING_KEY_PRIVATE" "$PRIVATE_KEY_B64"
  update_env "OAUTH_SIGNING_KEY_PUBLIC" "$PUBLIC_KEY_B64"
  update_env "SESSION_SECRET" "$SESSION_SECRET"
else
  info "Creating .env from .env.example"
  if [ -f "$PROJECT_ROOT/.env.example" ]; then
    cp "$PROJECT_ROOT/.env.example" "$ENV_FILE"
  else
    touch "$ENV_FILE"
  fi

  cat >> "$ENV_FILE" <<EOF

# =============================================================================
# Generated by setup-local-dev.sh — $(date -Iseconds)
# =============================================================================
OAUTH_SIGNING_KEY_PRIVATE=${PRIVATE_KEY_B64}
OAUTH_SIGNING_KEY_PUBLIC=${PUBLIC_KEY_B64}
SESSION_SECRET=${SESSION_SECRET}
EOF
fi

info ".env updated with signing keys and session secret"

# -- Summary -------------------------------------------------------------------
echo ""
echo "============================================================"
echo "  Local dev environment is ready!"
echo "============================================================"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Edit .env and fill in your Azure AD credentials:"
echo "     - AZURE_CLIENT_ID"
echo "     - AZURE_CLIENT_SECRET"
echo "     - AZURE_TENANT_ID"
echo ""
echo "  2. In Azure Portal, add this Redirect URI to your app:"
echo "     - http://localhost:3000/oauth/callback"
echo ""
echo "  3. Start the stack:"
echo "     docker compose up --build"
echo ""
echo "  4. Verify:"
echo "     - MCP Server health: http://localhost:3000/health"
echo "     - OAuth metadata:    http://localhost:3000/.well-known/oauth-authorization-server"
echo ""
echo "============================================================"
